export const USER_LOGIN_REQUEST = 'CONST_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'CONST_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'CONST_LOGIN_FAIL'
export const USER_LOGIN_LOGOUT = 'CONST_LOGIN_LOGOUT'


export const USER_REGISTER_REQUEST = 'CONST_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'CONST_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'CONST_REGISTER_FAIL'



export const USER_DETAILS_REQUEST = 'CONST_DETAILS_REQUEST'
export const USER_DETAILS_SUCCESS = 'CONST_DETAILS_SUCCESS'
export const USER_DETAILS_FAIL = 'CONST_DETAILS_FAIL'




export const USER_UPDATE_REQUEST = 'CONST_UPDATE_REQUEST'
export const USER_UPDATE_SUCCESS = 'CONST_UPDATE_SUCCESS'
export const USER_UPDATE_FAIL = 'CONST_UPDATE_FAIL'
export const USER_UPDATE_RESET = 'CONST_UPDATE_RESET'

